// frontend/src/App.svelte
<script>
  import ModelUsageChart from './lib/ModelUsageChart.svelte'

  const apiBase = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000'

  let file = null
  let isLoading = false
  let error = ''
  let result = null

  $: selectedFileName = file?.name ?? 'No file selected'
  $: canUpload = Boolean(file) && !isLoading
  $: globalRows = result ? Object.entries(result.global_stats) : []
  $: modelRows = result
    ? Object.entries(result.model_stats).sort(([, a], [, b]) => b - a)
    : []
  $: conversationRows = result ? Object.entries(result.conversation_stats) : []

  function onFileChange(event) {
    file = event.currentTarget.files?.[0] ?? null
  }

  async function onSubmit(event) {
    event.preventDefault()

    if (!file) {
      error = 'Please choose conversations.json first.'
      return
    }

    const formData = new FormData()
    formData.append('file', file)

    isLoading = true
    error = ''

    try {
      const response = await fetch(`${apiBase}/api/v1/upload/conversations`, {
        method: 'POST',
        body: formData,
      })
      const payload = await response.json()

      if (!response.ok) {
        throw new Error(payload?.detail ?? 'Upload failed.')
      }

      result = payload
    } catch (uploadError) {
      result = null
      error = uploadError instanceof Error ? uploadError.message : 'Upload failed.'
    } finally {
      isLoading = false
    }
  }
</script>

<main class="min-h-screen bg-slate-100 px-4 py-12 text-slate-900">
  <section class="mx-auto w-full max-w-5xl rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
    <h1 class="text-2xl font-semibold">ChatGPT Wrapped</h1>
    <p class="mt-2 text-sm text-slate-600">Upload your local conversations export and analyze it on localhost.</p>

    <form on:submit={onSubmit} class="mt-6 space-y-3">
      <div class="space-y-2">
        <label for="file" class="text-sm font-medium text-slate-700">conversations.json</label>
        <input
          id="file"
          type="file"
          accept=".json,application/json"
          class="block w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"
          on:change={onFileChange}
        />
        <p class="text-sm text-slate-600">{selectedFileName}</p>
      </div>

      <button
        type="submit"
        disabled={!canUpload}
        class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50"
      >
        {isLoading ? 'Analyzing...' : 'Upload + Analyze'}
      </button>
    </form>

    {#if error}
      <p class="mt-4 text-sm font-semibold text-red-700">{error}</p>
    {/if}

    {#if result}
      <p class="mt-4 text-sm font-semibold text-emerald-700">Upload complete. Results loaded.</p>

      <section class="mt-8 space-y-8">
        <div>
          <h2 class="text-lg font-semibold">Global Stats</h2>
          <div class="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {#each globalRows as [key, value]}
              <article class="rounded-lg border border-slate-200 bg-slate-50 p-3">
                <p class="text-xs uppercase tracking-wide text-slate-500">{key}</p>
                <p class="mt-1 text-xl font-semibold text-slate-900">{value.toLocaleString()}</p>
              </article>
            {/each}
          </div>
        </div>

        <div>
          <h2 class="text-lg font-semibold">Model Usage</h2>
          {#if modelRows.length === 0}
            <p class="mt-3 text-sm text-slate-600">No model stats found.</p>
          {:else}
            <div class="mt-3 rounded-lg border border-slate-200 bg-white p-3">
              <ModelUsageChart rows={modelRows} />
            </div>
          {/if}
        </div>

        <div>
          <h2 class="text-lg font-semibold">Conversation Stats</h2>
          <div class="mt-3 overflow-x-auto rounded-lg border border-slate-200">
            <table class="min-w-full text-left text-sm">
              <thead class="bg-slate-100 text-slate-700">
                <tr>
                  <th class="px-3 py-2 font-semibold">Conversation ID</th>
                  <th class="px-3 py-2 font-semibold">Msgs Sent</th>
                  <th class="px-3 py-2 font-semibold">Words Sent</th>
                  <th class="px-3 py-2 font-semibold">Msgs Recd</th>
                  <th class="px-3 py-2 font-semibold">Words Recd</th>
                </tr>
              </thead>
              <tbody>
                {#each conversationRows.slice(0, 25) as [conversationId, stats]}
                  <tr class="border-t border-slate-200">
                    <td class="px-3 py-2">{conversationId}</td>
                    <td class="px-3 py-2">{stats.convo_msgs_sent ?? 0}</td>
                    <td class="px-3 py-2">{stats.convo_words_sent ?? 0}</td>
                    <td class="px-3 py-2">{stats.convo_msgs_recd ?? 0}</td>
                    <td class="px-3 py-2">{stats.convo_words_recd ?? 0}</td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
          {#if conversationRows.length > 25}
            <p class="mt-2 text-sm text-slate-600">Showing first 25 conversations.</p>
          {/if}
        </div>
      </section>
    {/if}
  </section>
</main>

// frontend/src/App.tsx
import { DragEvent, FormEvent, useMemo, useState } from "react";

type UploadResult = {
  global_stats: Record<string, number>;
  conversation_stats: Record<string, Record<string, number>>;
  model_stats: Record<string, number>;
  meta?: Record<string, number>;
};

const apiBase = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8000";

export default function App() {
  const [file, setFile] = useState<File | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<UploadResult | null>(null);

  const canUpload = useMemo(() => Boolean(file) && !isLoading, [file, isLoading]);

  const onSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!file) {
      setError("Please choose conversations.json first.");
      return;
    }

    const formData = new FormData();
    formData.append("file", file);

    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch(`${apiBase}/api/v1/upload/conversations`, {
        method: "POST",
        body: formData,
      });
      const payload = (await response.json()) as UploadResult | { detail?: string };

      if (!response.ok) {
        const detail = "detail" in payload ? payload.detail : undefined;
        throw new Error(detail ?? "Upload failed.");
      }

      setResult(payload as UploadResult);
    } catch (uploadError) {
      setResult(null);
      setError(uploadError instanceof Error ? uploadError.message : "Upload failed.");
    } finally {
      setIsLoading(false);
    }
  };

  const onDropFile = (event: DragEvent<HTMLLabelElement>) => {
    event.preventDefault();
    const droppedFile = event.dataTransfer.files?.[0] ?? null;
    setFile(droppedFile);
  };

  const selectedFileName = file?.name ?? "No file selected";

  return (
    <main className="app-shell">
      <section className="panel">
        <h1>ChatGPT Wrapped</h1>
        <p>Upload your local conversations export and analyze it on localhost.</p>

        <form onSubmit={onSubmit} className="upload-form">
          <label
            htmlFor="file"
            className="drop-zone"
            onDragOver={(event) => event.preventDefault()}
            onDrop={onDropFile}
          >
            <span className="label">Drag + drop conversations.json here</span>
            <span className="sub-label">or click to choose file</span>
          </label>
          <input
            id="file"
            type="file"
            accept=".json,application/json"
            className="hidden-file-input"
            onChange={(event) => {
              const selected = event.target.files?.[0] ?? null;
              setFile(selected);
            }}
          />
          <p className="selected-file">{selectedFileName}</p>

          <button type="submit" disabled={!canUpload}>
            {isLoading ? "Analyzing..." : "Upload + Analyze"}
          </button>
        </form>

        {error ? <p className="error">{error}</p> : null}
        {result ? <p className="ok">Upload complete. Results loaded.</p> : null}

        {result ? <ResultsPanel result={result} /> : null}
      </section>
    </main>
  );
}

function ResultsPanel({ result }: { result: UploadResult }) {
  const modelRows = Object.entries(result.model_stats);
  const conversationRows = Object.entries(result.conversation_stats);
  const maxModelValue = Math.max(...modelRows.map(([, count]) => count), 1);

  return (
    <section className="results">
      <h2>Global Stats</h2>
      <div className="global-grid">
        {Object.entries(result.global_stats).map(([key, value]) => (
          <article key={key} className="stat-card">
            <p className="stat-key">{key}</p>
            <p className="stat-value">{value.toLocaleString()}</p>
          </article>
        ))}
      </div>

      <h2>Model Usage</h2>
      <div className="model-list">
        {modelRows.length === 0 ? <p>No model stats found.</p> : null}
        {modelRows.map(([modelId, count]) => {
          const widthPercent = Math.max(8, Math.round((count / maxModelValue) * 100));
          return (
            <div key={modelId} className="model-row">
              <span>{modelId}</span>
              <div className="bar-wrap">
                <div className="bar-fill" style={{ width: `${widthPercent}%` }} />
              </div>
              <strong>{count}</strong>
            </div>
          );
        })}
      </div>

      <h2>Conversation Stats</h2>
      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Conversation ID</th>
              <th>Msgs Sent</th>
              <th>Words Sent</th>
              <th>Msgs Recd</th>
              <th>Words Recd</th>
            </tr>
          </thead>
          <tbody>
            {conversationRows.slice(0, 25).map(([conversationId, stats]) => (
              <tr key={conversationId}>
                <td>{conversationId}</td>
                <td>{stats.convo_msgs_sent ?? 0}</td>
                <td>{stats.convo_words_sent ?? 0}</td>
                <td>{stats.convo_msgs_recd ?? 0}</td>
                <td>{stats.convo_words_recd ?? 0}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {conversationRows.length > 25 ? (
        <p className="sub-label">Showing first 25 conversations.</p>
      ) : null}
    </section>
  );
}
